FROM registry.access.redhat.com/ubi8/ubi

LABEL maintainer="MinIO Inc <dev@min.io>"

ENV GOPATH /go
ENV CGO_ENABLED 0
ENV GO111MODULE on

RUN  \
     yum  install -y --no-cache git && \
     git clone https://github.com/minio/minio && cd minio && \
     git checkout master && yum install -y go -v -ldflags "$(go run buildscripts/gen-ldflags.go)"

FROM alpine:3.12

ENV MINIO_UPDATE off
ENV MINIO_ACCESS_KEY_FILE=spinnakeradmin \
    MINIO_SECRET_KEY_FILE=spinnakeradmin \
    MINIO_KMS_MASTER_KEY_FILE=kms_master_key \
    MINIO_SSE_MASTER_KEY_FILE=sse_master_key

EXPOSE 9000

COPY --from=builder /go/bin/minio /usr/bin/minio
COPY --from=builder /go/minio/CREDITS /third_party/
COPY --from=builder /go/minio/dockerscripts/docker-entrypoint.sh /usr/bin/

RUN  \
     yum  install -y --no-cache ca-certificates 'curl>7.61.0' 'su-exec>=0.2' && \
     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]

VOLUME ["/data"]

CMD ["minio"]
